version: '3.1'
services:
  frontend:
    build: .
    container_name: react-frontend
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    