version: "3.7"
services:
  node-app:
    build: .
    ports:
      - "6500:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emash90
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
