version: "3.7"
services:
  node-app:
    build: .
    ports:
      - "6500:5000"
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      # - MONGO_URI=mongodb://mongo:27017/node-app
      # - JWT_SECRET=secret
      # - JWT_EXPIRES_IN=30d
      # - JWT_COOKIE_EXPIRES_IN=30
      # -