version: "3.7"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node server.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
  client:
    environment:
      - REACT_APP_API_URL=http://node-app:8080
    command: npm start
    ports:
      - "3000:3000"