version: "3.7"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
  node-app:
    build: .
    environment:
      - PORT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emash90
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb:/data/db
  
  redis:
    image: redis
    
  client:
    depends_on:
      - node-app
volumes:
  mongodb:
